version: '3'
volumes:
  postgresql_data:
    driver: local
services:
  postgresql:
    image: postgres:16.0-alpine3.18
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DATABASE: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5433"
    command: [ "postgres", "-c", "log_statement=all" ]